### ISSUE TITLE
Minor issue in wiki

### ISSUE THREAD

**Issue by orgbx** [UltimateAngular/aot-loader#1]
**What's gone wrong?**
in [aot-limitations](https://github.com/UltimateAngular/aot-loader/wiki/Limitations-with-AoT), last DO: 
``` javascript
...
export class ExampleComponent {
  /* @internal */
  @Input()
  exampleInput;
  // or just make it public
  @Input()
  anotherInput;
}
```
**What was meant to happen?**

`exampleInput` should be *private*
 
Oh, and thank you! This is going to be awesome!

**Comment by rynclark** [comment]
Fixed, nice one! :)
