### ISSUE TITLE
Compilation hangs with html-loader

### ISSUE THREAD

**Issue by blacksonic** [UltimateAngular/aot-loader#11]
**Is this a feature request or a bug report?**
Bug report

**What's gone wrong?**
When using HTML templates for components with `html-loader` and it processes attributes in tags like `<img src='./angular.png'>` it hangs in compilation. The Webpack config has an appropriate loader for images.

**What was meant to happen?**
Image attributes handled by the appropriate loader.

**Other information**
Node v6.5.0
Angular v2.4.8
Webpack v2.2.1
Typescript v2.0.10

Ubuntu 16.04

**Comment by rynclark** [comment]
Hey, I'm aware of why this is happening - will fix tonight

**Comment by Itrulia** [comment]
Will this also be fixed for loading HTML? We have a lot of Angular 1.5 components that have `template: require("./component.html")` in them, which would fail AoT for the whole application.

**Comment by rynclark** [comment]
Sorry for the delay, should be fixed now in 0.1.10. @Itrulia I haven't tested this at all on an Angular 1.5 code base - have you got an example repo I can test it out on?

**Comment by Itrulia** [comment]
I will create one for you tomorrow.
