### ISSUE TITLE
Tree Shaking Supoort

### ISSUE THREAD

**Issue by djarekg** [UltimateAngular/aot-loader#2]
Will Tree Shaking support be added to the aot-loader?

**Comment by rynclark** [comment]
There's not really anything we can do regarding tree shaking - this is implemented at the Webpack level rather than individual loaders/plugins.

Let me know if you've got any other thoughts regarding this.

**Comment by evanjmg** [comment]
You can implement tree shaking using webpack but you're code has to be configured properly into es2015 modules - from typescript to js will not tree shake as well - see this more info -
 https://medium.freecodecamp.com/tree-shaking-es6-modules-in-webpack-2-1add6672f31b
I'm noticed a lot of AOT loaders don't do this properly - @ngtools/webpack is the best one I've used but it's got some nasty performance issues.
