### ISSUE TITLE
Difference from ngtools/webpack

### ISSUE THREAD

**Issue by unlight** [UltimateAngular/aot-loader#21]
What is the difference between this loader and ngtools/webpack?
Feature list looks same.
Why it is started to develop?

**Comment by toddmotto** [comment]
Check the [wiki](https://github.com/UltimateAngular/aot-loader/wiki) for why this exists.

**Comment by unlight** [comment]
Wiki tells nothing about comparison of ngtools/webpack. Just mentioned ngc and no integration with webpack.

**Comment by toddmotto** [comment]
See the "What this loader does" section:

This loader will compile your application into AoT whilst you develop it, therefore minimising development time (as you don't need to wait for your components to be compiled in the browser) as well as making sure that your application is AoT ready whilst you develop it.

**Comment by irowbin** [comment]
I've tested both of these and I got more success with this 'UltimateAngular/aot-loader' than the 'ngtools/webpack' however it stuck sometime when the module loader reached about 11%.

**Comment by toddmotto** [comment]
There are some changes coming in Angular later this year to which AoT will be the default and JiT will disappear - possibly done via TypeScript transforms. We're not sure the lifespan of this tool because of that either as it'll be redundant at some stage.

**Comment by irowbin** [comment]
Angular  guys are wasting our time with this JIT while they've already planned to implement AoT as default.  (cool || !cool) = true; 🍰
