### ISSUE TITLE
Compilation hangs

### ISSUE THREAD

**Issue by blacksonic** [UltimateAngular/aot-loader#5]
**Is this a feature request or a bug report?**
Bug report

**What's gone wrong?**
After replacing `@ngtools/webpack` plugin and rule with `@ultimate/aot-loader` Webpack compilation hangs at 10%.

[Example repository](https://github.com/blacksonic/angular2-aot-cli-webpack-plugin)
Replace uncommented lines with `ngtools` in https://github.com/blacksonic/angular2-aot-cli-webpack-plugin/blob/master/webpack.aot.config.js and https://github.com/blacksonic/angular2-aot-cli-webpack-plugin/blob/master/webpack/module.aot.js . After that run `npm start` and Webpack bundling hangs.

**What was meant to happen?**
Should compile Angular application in AOT as before.

**Other information**
Node v6.5.0
Angular v2.4.8
Webpack v2.2.1
Typescript v2.0.10

Ubuntu 16.04

**Comment by chasemgray** [comment]
I'm also seeing this issue. I'm so happy someone else sees it too. I thought i was going crazy :)

**Comment by rynclark** [comment]
Investigating now!

**Comment by chasemgray** [comment]
Awesome! I can show you in a screenshare or something if it helps.

**Comment by rynclark** [comment]
I've got it reproduced locally, just trying to figure out why :) cheers though!

**Comment by rynclark** [comment]
So it appears that the compilation for the `.pug` file is not completing, causing it all to hang - looking into this

**Comment by chasemgray** [comment]
Me waiting for this...
![799806](https://cloud.githubusercontent.com/assets/68772/23234878/65b89ddc-f908-11e6-859b-50ec7ca29c0c.gif)

**Comment by rynclark** [comment]
Hey guys, fixed it in 0.1.8 - was an issue with pitch loaders, should all work now! (Would've been 0.1.7 but I left a `console.log` in, oops)

**Comment by blacksonic** [comment]
Works like a charm, thanks man!

**Comment by gitnik** [comment]
Still happens to me. And no `pug` files in sight

**Comment by Justus-Maier** [comment]
Still experiencing the same issue with v.0.1.15, Angular 4.0.0 with this starter:
https://github.com/antonybudianto/angular-webpack-starter.git

**Comment by irowbin** [comment]
I am also facing this issue as well. Angular v4.0.1  typescript v2.2.2, webpack v2x, @ultimate/aot-loader v0.1.15
![capture](https://cloud.githubusercontent.com/assets/13050078/24846620/72a6b2ca-1ddb-11e7-843d-f5365d96313b.PNG)

**Comment by maxfahl** [comment]
I have this problem as well with TS 2.2.2, webpack 2.3.3 and ultimate/aot-loader 0.1.16. Has anyone found a fix for this?

**Comment by rynclark** [comment]
Can you guys paste your webpack configs?

Cheers

**Comment by irowbin** [comment]
webpack.prod.js
`
var webpack = require('webpack');
var webpackMerge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var commonConfig = require('./webpack.common.js');
var aotLoader = require('@ultimate/aot-loader');
var helpers = require('./helpers');

const ENV = process.env.NODE_ENV = process.env.ENV = 'production';

console.log('###### ----------> USING PRODUCTION <---------- ######');

module.exports = webpackMerge(commonConfig, {
  // devtool: 'source-map',
  output: {
    path: helpers.root('dist'),
    publicPath: '/',
    filename: '[name].[hash].js',
    chunkFilename: '[id].[chunkhash].js'
  },

  plugins: [
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      // https://github.com/angular/angular/issues/10618
      mangle: {
        keep_fnames: true,
  
      },
      compress: {
        //   sourceMap: true
        // remove warnings
        warnings: false,

        // Drop console statements
        drop_console: true
      },
   
    }),
    new ExtractTextPlugin('[name].[hash].css'),
    new webpack.DefinePlugin({
      'process.env': {
        'ENV': JSON.stringify(ENV)
      }
    }),
    new webpack.LoaderOptionsPlugin({
      htmlLoader: {
        minimize: false // workaround for ng2
      }
    }),

  
    new aotLoader.AotPlugin({
      tsConfig: './tsconfig.json',
      entryModule: './src/app/app.module#AppModule',

    }),
    

  ]
});
`
webpack.common.js
`var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');
var ChunkManifestPlugin = require('chunk-manifest-webpack2-plugin');
var WebpackChunkHash = require('webpack-chunk-hash');
var environment = (process.env.NODE_ENV || "development").trim();

var compilersToUse = environment === 'development'
  ? [
    'awesome-typescript-loader',
    'angular2-template-loader',
    'angular2-router-loader',
  ] //  development

  : [ '@ultimate/aot-loader']; //  AoT compilation

module.exports = {
  entry: {
    'polyfills': './src/polyfills.ts',
    'vendor': './src/vendor.ts',
    'themeScript': './src/theme-scripts.ts',
    // 'app': './src/main-aot.ts',
    'app': './src/main.ts',
    'theme-styles': './src/theme-styles.ts'
  },
  resolve: {
    extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html'],

  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        use: compilersToUse
      },
      {
        test: /\.html$/,
        use: 'html-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        use: 'file-loader?name=assets/[name].[hash].[ext]'
      },
      {
        test: /\.css$/,
        exclude: helpers.root('src', 'app'),
        use: ExtractTextPlugin.extract({ fallback: 'style-loader', use: ['css-loader'] })
      },
      {
        test: /\.css$/,
        include: helpers.root('src', 'app'),
        use: 'raw-loader'
      },
      {
        test: /\.component\.css$/,
        use: [
          { loader: 'raw-loader' },
        ]
      },
  

    ],
  },

  plugins: [
    // Workaround for angular/angular#11580
    new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /angular(\\|\/)core(\\|\/)@angular/,
      helpers.root('./src'), // location of your src
      {} // a map of your routes
    ),

    new webpack.optimize.CommonsChunkPlugin({
      name: ['app', 'themeScript', 'vendor', 'polyfills', ]
     
    }),
   

    new HtmlWebpackPlugin({
      template: 'src/index.html',
      fileName: 'index.html',
      hash: true,
      minify: {
        removeAttributeQuotes: false,//Remove quotes around attributes when possible
        minifyJS: true, //Minify JavaScript in script elements and event attributes (uses UglifyJS)
        minifyCSS: true, //Minify CSS in style elements and style attributes (uses clean-css)
        removeComments: true, // Strip HTML comments
        removeTagWhitespace: true, //Remove space between attributes whenever possible. Note that this will result in invalid HTML!
        trimCustomFragments: true, // Trim white space around ignoreCustomFragments.
        collapseWhitespace: true, //Collapse white space that contributes to text nodes in a document tree
        collapseInlineTagWhitespace: true, //Don't leave any spaces between display:inline; elements when collapsing. Must be used in conjunction with collapseWhitespace=true
      }
    }),


    new webpack.ProvidePlugin({
      //for jquery
      $: "jquery",
      jQuery: "jquery",
      //for toastr 
      toastr: "toastr",

    }),
   
  ]
};`

that's all i got. Thanks 👍  @rynclark
