### ISSUE TITLE
Using aot-loader in karma jasmine tests

### ISSUE THREAD

**Issue by chasemgray** [UltimateAngular/aot-loader#7]
Is there anyway to get this loader working where it will run unit tests using the AoT compiled code?

**Comment by rynclark** [comment]
Have you tried https://github.com/webpack-contrib/karma-webpack?

**Comment by chasemgray** [comment]
I was just wondering if this will work since this plugin dynamically replaces the platformBrowserDynamic().bootstrapModule(AppModule) line and in the tests it is using a different object to init.
```

beforeAll(() => {
  TestBed.initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting()
  );
});
```

**Comment by rynclark** [comment]
Seems that `TestBed` doesn't allow you to use AoT compiled components and must use JiT instead
